Repository OpenVoiceOS/ovos-utils, pull requests merged in 2022-02, with the labels that each got.

#22 feat/license tests workflow
  .github/workflows/license_tests.yml
  test/license_tests.py
Labels: tests and automation

#28 Fix/core module detection + refactor xdg config path utils
  ovos_utils/configuration.py
Labels: bug

#29 feat/packaging workflows
  .github/workflows/build_tests.yml
  .github/workflows/license_tests.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .github/workflows/unit_tests.yml
  CHANGELOG.md
  ovos_utils/version.py
  ovos_utils/versioning/__init__.py
  ovos_utils/versioning/outils_versions.py
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  setup.py
  test/unittests/test_color.py
  test/unittests/test_json_helpers.py
  test/unittests/test_parse.py
  test/unittests/test_ssml.py
  test/unittests/test_utils.py
  version_bump.py
Labels: refactor

#30 Refactor/workflows from template
  .github/workflows/dev2master.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  MANIFEST.in
Labels: refactor

#31 Handle stopwatch.stop before started
  .github/workflows/build_tests.yml
  ovos_utils/metrics.py
  test/test_metrics.py
Labels: bug
