Repository OpenVoiceOS/ovos-utils, pull requests merged in 2022-05, with the labels that each got.

#41 add sdist
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
Labels: packaging

#42 refactor/migrate_adapt_boilerplate
  ovos_utils/intents/__init__.py
  ovos_utils/skills/__init__.py
Labels: refactor, packaging

#45 support ovos-shell
  ovos_utils/gui.py
Labels: bug, packaging

#47 feat/lang_utils
  ovos_utils/configuration.py
  ovos_utils/messagebus.py
Labels: enhancement
