Repository OpenVoiceOS/ovos-utils, pull requests merged in 2023-05, with the labels that each got.

#138 fix/new_bug
  ovos_utils/messagebus.py
Labels: bug

#139 feat/skill_api
  ovos_utils/skills/api.py
Labels: enhancement

#141 port LF time utils
  ovos_utils/time.py
  test/unittests/test_time.py
Labels: enhancement

#143 Configurable skills base directory
  .github/workflows/build_tests.yml
  ovos_utils/skills/locations.py
  test/unittests/test_skills.py
Labels: bug

#147 Enable Log name and level overrides from envvars
  ovos_utils/log.py
  test/unittests/test_log.py
Labels: enhancement

#148 fix/filewatcher
  ovos_utils/file_utils.py
  test/unittests/test_file_utils.py
Labels: bug

#145 Add unit test coverage for SkillApi
  test/unittests/test_skills.py
Labels: tests and automation
