Repository OpenVoiceOS/ovos-utils, pull requests merged in 2023-06, with the labels that each got.

#158 Annotate GUI Module and refactor resource resolution
  ovos_utils/gui.py
Labels: bug, documentation

#159 Codecov automation
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
Labels: bug, tests and automation

#160 Fix codecov automation
  .github/workflows/unit_tests.yml
  test/unittests/test_time.py
Labels: tests and automation

#140 bus upload qml
  ovos_utils/gui.py
  test/unittests/test_gui.py
  test/unittests/test_ui/ui/subdir/test.qml
  test/unittests/test_ui/ui/test.qml
Labels: enhancement

#161 Add deprecation log helpers
  ovos_utils/__init__.py
  ovos_utils/configuration.py
  ovos_utils/dialog.py
  ovos_utils/enclosure/__init__.py
  ovos_utils/events.py
  ovos_utils/file_utils.py
  ovos_utils/fingerprinting.py
  ovos_utils/gui.py
  ovos_utils/log.py
  ovos_utils/messagebus.py
  ovos_utils/ovos_service_api.py
  ovos_utils/process_utils.py
  ovos_utils/signal.py
  ovos_utils/skills/__init__.py
  ovos_utils/skills/audioservice.py
  ovos_utils/skills/locations.py
  ovos_utils/skills/settings.py
  ovos_utils/sound/alsa.py
  ovos_utils/sound/pulse.py
  test/unittests/deprecation_helper.py
  test/unittests/test_events.py
  test/unittests/test_log.py
Labels: enhancement

#166 Fix dev branch coverage action
  .github/workflows/coverage.yml
Labels: tests and automation

#170 Add unit tests for shutdown/restart
  ovos_utils/system.py
  test/unittests/test_system.py
Labels: tests and automation
