Repository OpenVoiceOS/ovos-utils, pull requests merged in 2023-12, with the labels that each got.

#202 update imports for py 3.10 compat
  ovos_utils/enclosure/mark1/faceplate/__init__.py
Labels: bug

#206 LAST ALPHA
  .github/workflows/build_tests.yml
  .github/workflows/unit_tests.yml
  .gitignore
  ovos_utils/enclosure/__init__.py
  ovos_utils/enclosure/api.py
  ovos_utils/enclosure/mark1/__init__.py
  ovos_utils/enclosure/mark1/eyes/__init__.py
  ovos_utils/enclosure/mark1/faceplate/__init__.py
  ovos_utils/enclosure/mark1/faceplate/animations.py
  ovos_utils/enclosure/mark1/faceplate/cellular_automaton.py
  ovos_utils/enclosure/mark1/faceplate/icons.py
  ovos_utils/events.py
  ovos_utils/intents/__init__.py
  ovos_utils/intents/converse.py
  ovos_utils/intents/intent_service_interface.py
  ovos_utils/intents/layers.py
  ovos_utils/messagebus.py
  ovos_utils/skills/api.py
  ovos_utils/skills/audioservice.py
  ovos_utils/skills/locations.py
  ovos_utils/skills/settings.py
  requirements/test.txt
  test/unittests/test_skills.py
Labels: refactor, packaging

#210 0.0.32post1
  ovos_utils/enclosure/api.py
  ovos_utils/events.py
  ovos_utils/fakebus.py
  ovos_utils/file_utils.py
  ovos_utils/gui.py
  ovos_utils/intents/intent_service_interface.py
  ovos_utils/messagebus.py
  ovos_utils/skills/__init__.py
  ovos_utils/skills/api.py
  ovos_utils/skills/audioservice.py
  test/unittests/test_enclosure.py
  test/unittests/test_events.py
  test/unittests/test_gui.py
  test/unittests/test_intents.py
  test/unittests/test_skills.py
Labels: bug, refactor, packaging

#211 Update version.py
  ovos_utils/version.py
  setup.py
Labels: bug, tests and automation, packaging

#212 0.0.37post2
  ovos_utils/gui.py
  ovos_utils/intents/converse.py
  ovos_utils/intents/intent_service_interface.py
  ovos_utils/intents/layers.py
  ovos_utils/version.py
  test/unittests/test_gui.py
Labels: packaging

#203 Feat/ovos logs script
  ovos_utils/log.py
  ovos_utils/log_parser.py
  readme.md
  requirements/requirements.txt
  setup.py
Labels: enhancement
