Repository OpenVoiceOS/ovos-utils, pull requests merged in 2023-09, with the labels that each got.

#186 IntentServiceInterface Tests and Minor Fixes
  ovos_utils/intents/intent_service_interface.py
  test/unittests/test_intents.py
Labels: documentation, enhancement, tests and automation

#191 refactor/less_gui_spam
  ovos_utils/gui.py
Labels: refactor

#192 hotfix/gui_sync
  ovos_utils/gui.py
Labels: bug

#189 Support "logging" section to allow per-service log level changes
  ovos_utils/log.py
Labels: enhancement
