Repository OpenVoiceOS/ovos-utils, pull requests merged in 2024-01, with the labels that each got.

#215 refactor/ocp_utils
  ovos_utils/ocp.py
Labels: refactor, packaging

#216 refactor/ocp_utils
  ovos_utils/ocp.py
  requirements/requirements.txt
Labels: enhancement

#218 OCP serialization
  ovos_utils/ocp.py
Labels: enhancement

#219 clarify datetime arg
  ovos_utils/log_parser.py
Labels: documentation

#220 fix/restore deprecated OCP enums compat
  ovos_utils/ocp.py
Labels: bug

#221 fix/ocp_playlist
  ovos_utils/ocp.py
  test/unittests/test_ocp_media.py
Labels: bug, tests and automation
