Repository OpenVoiceOS/ovos-utils, pull requests merged in 2024-11, with the labels that each got.

#291 chore: update docstrings and type hints
  ovos_utils/skills.py
  ovos_utils/system.py
Labels: ignore-for-release

#301 feat:oauth utils to ovos-utils and deprecate backend-client
  ovos_utils/oauth.py
  requirements/requirements.txt
Labels: feature

#304 fix: remove mycroft-bus-client compat
  ovos_utils/events.py
  ovos_utils/fakebus.py
  ovos_utils/messagebus.py
  test/unittests/test_event_scheduler.py
  test/unittests/test_events.py
Labels: fix

#306 fix: restore backwards compat
  ovos_utils/messagebus.py
Labels: fix

#310 fix: this time fix compat for realz
  ovos_utils/fakebus.py
Labels: fix
